<a href="https://colab.research.google.com/github/p1440788-ops/semantic-research-paper-search-engine/blob/main/CBSOT_SIP_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.7.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.36.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.5.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.6.17)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [2]:
from datasets import load_dataset

In [3]:
dataset=load_dataset('CShorten/ML-ArXiv-Papers',split='train')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

In [4]:
dataset

Dataset({
    features: ['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'],
    num_rows: 117592
})

In [5]:
print(dataset)

Dataset({
    features: ['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'],
    num_rows: 117592
})

In [6]:
dataset[0]

{'Unnamed: 0.1': 0,
 'Unnamed: 0': 0.0,
 'title': 'Learning from compressed observations',
 'abstract': '  The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rate functions. The ideas are\nillustrated on the example of nonparametric regression in Gaussian noise.\n'}

In [7]:
import pandas as pd

In [8]:
df=pd.DataFrame(dataset)

In [9]:
df

,Unnamed: 0.1,Unnamed: 0,title,abstract
0,0,0.0,Learning from compressed observations,The problem of statistical learning is to co...
1,1,1.0,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,2,2.0,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,3,3.0,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,4,4.0,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...,...,...
117587,4995,NaN,Detecting COVID-19 Conspiracy Theories with Tr...,The sharing of fake news and conspiracy theori...
117588,4996,NaN,Fair Feature Subset Selection using Multiobjec...,The feature subset selection problem aims at s...
117589,4997,NaN,A Simple Duality Proof for Wasserstein Distrib...,We present a short and elementary proof of the...
117590,4998,NaN,Combined Learning of Neural Network Weights fo...,"We introduce CoLN, Combined Learning of Neural..."
117591,4999,NaN,Adapting and Evaluating Influence-Estimation M...,Influence estimation analyzes how changes to t...

In [10]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'], dtype='object')

In [11]:
df=df[['title','abstract']]

In [12]:
df

,title,abstract
0,Learning from compressed observations,The problem of statistical learning is to co...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...
117587,Detecting COVID-19 Conspiracy Theories with Tr...,The sharing of fake news and conspiracy theori...
117588,Fair Feature Subset Selection using Multiobjec...,The feature subset selection problem aims at s...
117589,A Simple Duality Proof for Wasserstein Distrib...,We present a short and elementary proof of the...
117590,Combined Learning of Neural Network Weights fo...,"We introduce CoLN, Combined Learning of Neural..."
117591,Adapting and Evaluating Influence-Estimation M...,Influence estimation analyzes how changes to t...

In [13]:
df.shape

(117592, 2)

In [14]:
df=df.head(15000)

In [15]:
df.shape

(15000, 2)

In [16]:
df.isnull().sum()

title       0
abstract    0
dtype: int64

In [17]:
df['Paper_text']=df['title']+" "+df['abstract']

/tmp/ipykernel_15810/1613086540.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Paper_text']=df['title']+" "+df['abstract']

In [18]:
df['Paper_text'].head()

0    Learning from compressed observations   The pr...
1    Sensor Networks with Random Links: Topology De...
2    The on-line shortest path problem under partia...
3    A neural network approach to ordinal regressio...
4    Parametric Learning and Monte Carlo Optimizati...
Name: Paper_text, dtype: object

In [19]:
type(df)

pandas.core.frame.DataFrame

In [20]:
print(df['Paper_text'].iloc[0])

Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random
variable $Y$ as a function of a related random variable $X$ on the basis of an
i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable
predictors are drawn from some specified class, and the goal is to approach
asymptotically the performance (expected loss) of the best predictor in the
class. We consider the setting in which one has perfect observation of the
$X$-part of the sample, while the $Y$-part has to be communicated at some
finite bit rate. The encoding of the $Y$-values is allowed to depend on the
$X$-values. Under suitable regularity conditions on the admissible predictors,
the underlying family of probability distributions and the loss function, we
give an information-theoretic characterization of achievable predictor
performance in terms of conditional distortion-rate functions. The ideas are
illustrated on the example of nonparametric regression in Gaussian noise.

In [21]:
from sentence_transformers import SentenceTransformer

The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.

0it [00:00, ?it/s]

WARNING:torchao.kernel.intmm:Warning: Detected no triton, on systems without Triton certain kernels will not work

In [22]:
model=SentenceTransformer('all-MiniLM-L6-v2')

In [23]:
print(type(model))

<class 'sentence_transformers.sentence_transformer.model.SentenceTransformer'>

In [24]:
sample_text=df['Paper_text'].iloc[0]

In [25]:
sample_text

'Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rate functions. The ideas are\nillustrated on the example of nonparametric regression in Gaussian noise.\n'

In [26]:
embedding=model.encode(sample_text)

In [27]:
print(type(embedding))

<class 'numpy.ndarray'>

In [28]:
print(embedding.shape)

(384,)

In [29]:
df['Papertext']=df['Paper_text'].str.replace('\n',' ',regex=False)

/tmp/ipykernel_15810/1427937894.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Papertext']=df['Paper_text'].str.replace('\n',' ',regex=False)

In [30]:
df['Papertext']=df['Paper_text'].str.strip

/tmp/ipykernel_15810/3732735163.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Papertext']=df['Paper_text'].str.strip

In [31]:
sample_text=df['Paper_text'].iloc[0]

In [32]:
sample_text

'Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rate functions. The ideas are\nillustrated on the example of nonparametric regression in Gaussian noise.\n'

In [33]:
embedding=model.encode(sample_text)
print(type(embedding))
print(embedding.shape)

<class 'numpy.ndarray'>
(384,)

In [34]:
embedding[:16]

array([-0.1315641 , -0.00678266, -0.00367612,  0.03265158,  0.11219642,
        0.01227267,  0.09816719, -0.0900523 ,  0.04231161, -0.01977348,
       -0.03308417,  0.07452948,  0.10632038, -0.02060429, -0.02052106,
        0.00169493], dtype=float32)

In [35]:
sample_embedding=model.encode(df['Paper_text'].head(5).to_list())

In [36]:
print(sample_embedding.shape)

(5, 384)

In [37]:
from sklearn.metrics.pairwise import cosine_similarity

In [38]:
similarity=cosine_similarity(sample_embedding[0].reshape(1,-1),sample_embedding[0].reshape(1,-1))

print(similarity)

[[1.0000001]]

In [39]:
similarity=cosine_similarity(sample_embedding[0].reshape(1,-1),sample_embedding[1].reshape(1,-1))

print(similarity)

[[0.36625272]]

In [40]:
for i in range(5):
  sim=cosine_similarity(sample_embedding[0].reshape(1,-1),sample_embedding[i].reshape(1,-1))
  print(sim)

[[1.0000001]]
[[0.36625272]]
[[0.33522844]]
[[0.15505108]]
[[0.37421533]]

In [41]:
import os
import numpy as np

# The embedding dimension is 384, as observed in previous cell outputs.
EXPECTED_EMBEDDING_DIM = 384

embeddings = None
embedding_file_path = 'paper_embeddings.npy'

if os.path.exists(embedding_file_path):
  print('Attempting to load saved embeddings...')
  try:
    loaded_embeddings = np.load(embedding_file_path)
    # Check if the number of rows matches the current DataFrame length
    # and if the embedding dimension is correct.
    if loaded_embeddings.shape[0] == len(df) and loaded_embeddings.shape[1] == EXPECTED_EMBEDDING_DIM:
      embeddings = loaded_embeddings
      print('Embeddings loaded successfully.')
    else:
      print(f'Saved embeddings have an incorrect shape {loaded_embeddings.shape}, expected ({len(df)}, {EXPECTED_EMBEDDING_DIM}).')
      print('Deleting old embeddings file and regenerating...')
      os.remove(embedding_file_path)
  except ValueError as e:
    print(f'Error loading embeddings from {embedding_file_path} due to shape mismatch: {e}.')
    print('Deleting old embeddings file and regenerating...')
    if os.path.exists(embedding_file_path): # Ensure it exists before trying to remove
        os.remove(embedding_file_path)
  except Exception as e:
    print(f'An unexpected error occurred while loading embeddings from {embedding_file_path}: {e}.')
    print('Deleting old embeddings file and regenerating...')
    if os.path.exists(embedding_file_path): # Ensure it exists before trying to remove
        os.remove(embedding_file_path)

if embeddings is None:
  print('Generating embeddings...')
  embeddings = model.encode(df['Paper_text'].to_list(), batch_size=32, show_progress_bar=True)
  np.save(embedding_file_path, embeddings)
  print('Embeddings saved successfully.')

Attempting to load saved embeddings...
Embeddings loaded successfully.

In [42]:
print(embeddings.shape)
print(type(embeddings))

(15000, 384)
<class 'numpy.ndarray'>

In [43]:
!pip install faiss-cpu

Requirement already satisfied: faiss-cpu in /usr/local/lib/python3.12/dist-packages (1.14.3)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.2)

In [44]:
import faiss

In [45]:
faiss.normalize_L2(embeddings)

In [46]:
index=faiss.IndexFlatIP(384)

In [47]:
index.add(embeddings)

In [48]:
print(index.ntotal)

15000

In [49]:
query='deep learning for medical image analysis'
query_embedding=model.encode([query])
query_embedding.shape

(1, 384)

In [50]:
faiss.normalize_L2(query_embedding)

In [51]:
D,I=index.search(query_embedding,5)
print(D)

[[0.6807244  0.67092204 0.65219975 0.62811744 0.61311525]]

In [52]:
import os
import faiss

faiss_index_file_path = 'paper_faiss.index'
index = None

if os.path.exists(faiss_index_file_path):
  print('Attempting to load existing FAISS index...')
  try:
    index = faiss.read_index(faiss_index_file_path)
    print('FAISS index loaded successfully.')
  except RuntimeError as e:
    print(f"Error loading FAISS index from {faiss_index_file_path}: {e}.")
    print('Deleting corrupted FAISS index file and regenerating...')
    os.remove(faiss_index_file_path)
  except Exception as e:
    print(f"An unexpected error occurred while loading FAISS index from {faiss_index_file_path}: {e}.")
    print('Deleting old FAISS index file and regenerating...')
    os.remove(faiss_index_file_path)

if index is None:
  print('Creating new FAISS index...')
  # The 'embeddings' variable from kernel state (0J-iRcwGZjph) is (15000, 384)
  # and should be used for building the index.
  faiss.normalize_L2(embeddings)
  index = faiss.IndexFlatIP(embeddings.shape[1]) # Use the actual embedding dimension
  index.add(embeddings)
  faiss.write_index(index, faiss_index_file_path)
  print('FAISS index saved successfully.')

Attempting to load existing FAISS index...
FAISS index loaded successfully.

In [53]:
print(df.iloc[10466]['title'])

A Perspective on Deep Imaging

In [54]:
print(df.iloc[10466]['abstract'])

  The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance in clinical and
preclinical applications. To realize the full impact of machine learning on
medical imaging, major challenges must be addressed.

In [55]:
def search_paper(query,k=5):
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  return D,I

In [56]:
D,I=search_paper('deep learning for medical image analysis')
print(D)
print(I)

[[0.6807244  0.67092204 0.65219975 0.62811744 0.61311525]]
[[10466 13730 11873 12691 11282]]

In [57]:
def search_paper(query,k=5):
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  for score,idx in zip(D[0],I[0]):
    print('Title: ',df.iloc[idx]["title"])
    print('Title',df.iloc[idx]['abstract'][:500])
    print('Abstract: ',df.iloc[idx]["abstract"])
    print('Score:', score)

In [58]:
search_paper('deep learning for medical image analysis')

Title:  A Perspective on Deep Imaging
Title   The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance
Abstract:    The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance in clinical and
preclinical applications. To realize the full impact of machine learning on
medical imaging, major challenges must be addressed.

Score: 0.6807244
Title:  Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?
Title   Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure proper convergence. A promising alternative is to fine-tune
a CNN that has been pre-trained using, for instance, a large set of labeled
natural images. However, the substantial differences between natural and
medical images may advise against such knowledge transfer. In this paper, we
seek to answer the following centra
Abstract:    Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure proper convergence. A promising alternative is to fine-tune
a CNN that has been pre-trained using, for instance, a large set of labeled
natural images. However, the substantial differences between natural and
medical images may advise against such knowledge transfer. In this paper, we
seek to answer the following central question in the context of medical image
analysis: \emph{Can the use of pre-trained deep CNNs with sufficient
fine-tuning eliminate the need for training a deep CNN from scratch?} To
address this question, we considered 4 distinct medical imaging applications in
3 specialties (radiology, cardiology, and gastroenterology) involving
classification, detection, and segmentation from 3 different imaging
modalities, and investigated how the performance of deep CNNs trained from
scratch compared with the pre-trained CNNs fine-tuned in a layer-wise manner.
Our experiments consistently demonstrated that (1) the use of a pre-trained CNN
with adequate fine-tuning outperformed or, in the worst case, performed as well
as a CNN trained from scratch; (2) fine-tuned CNNs were more robust to the size
of training sets than CNNs trained from scratch; (3) neither shallow tuning nor
deep tuning was the optimal choice for a particular application; and (4) our
layer-wise fine-tuning scheme could offer a practical way to reach the best
performance for the application at hand based on the amount of available data.

Score: 0.67092204
Title:  Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection
Title   The classification of MRI images according to the anatomical field of view is
a necessary task to solve when faced with the increasing quantity of medical
images. In parallel, advances in deep learning makes it a suitable tool for
computer vision problems. Using a common architecture (such as AlexNet)
provides quite good results, but not sufficient for clinical use. Improving the
model is not an easy task, due to the large number of hyper-parameters
governing both the architecture and the trai
Abstract:    The classification of MRI images according to the anatomical field of view is
a necessary task to solve when faced with the increasing quantity of medical
images. In parallel, advances in deep learning makes it a suitable tool for
computer vision problems. Using a common architecture (such as AlexNet)
provides quite good results, but not sufficient for clinical use. Improving the
model is not an easy task, due to the large number of hyper-parameters
governing both the architecture and the training of the network, and to the
limited understanding of their relevance. Since an exhaustive search is not
tractable, we propose to optimize the network first by random search, and then
by an adaptive search based on Gaussian Processes and Probability of
Improvement. Applying this method on a large and varied MRI dataset, we show a
substantial improvement between the baseline network and the final one (up to
20\% for the most difficult classes).

Score: 0.65219975
Title:  High-Resolution Breast Cancer Screening with Multi-View Deep
  Convolutional Neural Networks
Title   Advances in deep learning for natural images have prompted a surge of
interest in applying similar techniques to medical images. The majority of the
initial attempts focused on replacing the input of a deep convolutional neural
network with a medical image, which does not take into consideration the
fundamental differences between these two types of images. Specifically, fine
details are necessary for detection in medical images, unlike in natural images
where coarse structures matter most. Th
Abstract:    Advances in deep learning for natural images have prompted a surge of
interest in applying similar techniques to medical images. The majority of the
initial attempts focused on replacing the input of a deep convolutional neural
network with a medical image, which does not take into consideration the
fundamental differences between these two types of images. Specifically, fine
details are necessary for detection in medical images, unlike in natural images
where coarse structures matter most. This difference makes it inadequate to use
the existing network architectures developed for natural images, because they
work on heavily downscaled images to reduce the memory requirements. This hides
details necessary to make accurate predictions. Additionally, a single exam in
medical imaging often comes with a set of views which must be fused in order to
reach a correct conclusion. In our work, we propose to use a multi-view deep
convolutional neural network that handles a set of high-resolution medical
images. We evaluate it on large-scale mammography-based breast cancer screening
(BI-RADS prediction) using 886,000 images. We focus on investigating the impact
of the training set size and image size on the prediction accuracy. Our results
highlight that performance increases with the size of training set, and that
the best performance can only be achieved using the original resolution. In the
reader study, performed on a random subset of the test set, we confirmed the
efficacy of our model, which achieved performance comparable to a committee of
radiologists when presented with the same data.

Score: 0.62811744
Title:  Deep Learning for the Classification of Lung Nodules
Title   Deep learning, as a promising new area of machine learning, has attracted a
rapidly increasing attention in the field of medical imaging. Compared to the
conventional machine learning methods, deep learning requires no hand-tuned
feature extractor, and has shown a superior performance in many visual object
recognition applications. In this study, we develop a deep convolutional neural
network (CNN) and apply it to thoracic CT images for the classification of lung
nodules. We present the CNN ar
Abstract:    Deep learning, as a promising new area of machine learning, has attracted a
rapidly increasing attention in the field of medical imaging. Compared to the
conventional machine learning methods, deep learning requires no hand-tuned
feature extractor, and has shown a superior performance in many visual object
recognition applications. In this study, we develop a deep convolutional neural
network (CNN) and apply it to thoracic CT images for the classification of lung
nodules. We present the CNN architecture and classification accuracy for the
original images of lung nodules. In order to understand the features of lung
nodules, we further construct new datasets, based on the combination of
artificial geometric nodules and some transformations of the original images,
as well as a stochastic nodule shape model. It is found that simplistic
geometric nodules cannot capture the important features of lung nodules.

Score: 0.61311525

In [59]:
!pip install transformers==4.46.3

Requirement already satisfied: transformers==4.46.3 in /usr/local/lib/python3.12/dist-packages (4.46.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (3.29.4)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (0.36.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (2.32.4)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (0.20.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (0.8.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.46.3) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.46.3) (1.5.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.46.3) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (2026.6.17)

In [60]:
from transformers import pipeline

In [61]:
from transformers import pipeline

summarizer=pipeline(
    task='summarization',model='facebook/bart-large-cnn')

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [62]:
type(summarizer)

transformers.pipelines.text2text_generation.SummarizationPipeline

In [63]:
summary=summarizer(df.iloc[10466]['abstract'],max_length=120,min_length=40)
print(summary)

[{'summary_text': 'The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.'}]

In [64]:
for score,idx in zip(D[0],I[0]):
    print('Title: ',df.iloc[idx]["title"])
    print('Title',df.iloc[idx]['abstract'][:500])
    print('Abstract: ',df.iloc[idx]["abstract"])
    print('Score:', score)
    print()
    summary=summarizer(df.iloc[idx]['abstract'],max_length=120,min_length=40)
    print('Summary: ',summary[0]['summary_text'])
    print()

Title:  A Perspective on Deep Imaging
Title   The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance
Abstract:    The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance in clinical and
preclinical applications. To realize the full impact of machine learning on
medical imaging, major challenges must be addressed.

Score: 0.6807244

Summary:  The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.

Title:  Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?
Title   Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure proper convergence. A promising alternative is to fine-tune
a CNN that has been pre-trained using, for instance, a large set of labeled
natural images. However, the substantial differences between natural and
medical images may advise against such knowledge transfer. In this paper, we
seek to answer the following centra
Abstract:    Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure proper convergence. A promising alternative is to fine-tune
a CNN that has been pre-trained using, for instance, a large set of labeled
natural images. However, the substantial differences between natural and
medical images may advise against such knowledge transfer. In this paper, we
seek to answer the following central question in the context of medical image
analysis: \emph{Can the use of pre-trained deep CNNs with sufficient
fine-tuning eliminate the need for training a deep CNN from scratch?} To
address this question, we considered 4 distinct medical imaging applications in
3 specialties (radiology, cardiology, and gastroenterology) involving
classification, detection, and segmentation from 3 different imaging
modalities, and investigated how the performance of deep CNNs trained from
scratch compared with the pre-trained CNNs fine-tuned in a layer-wise manner.
Our experiments consistently demonstrated that (1) the use of a pre-trained CNN
with adequate fine-tuning outperformed or, in the worst case, performed as well
as a CNN trained from scratch; (2) fine-tuned CNNs were more robust to the size
of training sets than CNNs trained from scratch; (3) neither shallow tuning nor
deep tuning was the optimal choice for a particular application; and (4) our
layer-wise fine-tuning scheme could offer a practical way to reach the best
performance for the application at hand based on the amount of available data.

Score: 0.67092204

Summary:  Training a deep convolutional neural network from scratch is difficult because it requires a large amount of labeled training data. A promising alternative is to fine-tune a CNN that has been pre-trained using, for instance, a large set of labeled natural images.

Title:  Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection
Title   The classification of MRI images according to the anatomical field of view is
a necessary task to solve when faced with the increasing quantity of medical
images. In parallel, advances in deep learning makes it a suitable tool for
computer vision problems. Using a common architecture (such as AlexNet)
provides quite good results, but not sufficient for clinical use. Improving the
model is not an easy task, due to the large number of hyper-parameters
governing both the architecture and the trai
Abstract:    The classification of MRI images according to the anatomical field of view is
a necessary task to solve when faced with the increasing quantity of medical
images. In parallel, advances in deep learning makes it a suitable tool for
computer vision problems. Using a common architecture (such as AlexNet)
provides quite good results, but not sufficient for clinical use. Improving the
model is not an easy task, due to the large number of hyper-parameters
governing both the architecture and the training of the network, and to the
limited understanding of their relevance. Since an exhaustive search is not
tractable, we propose to optimize the network first by random search, and then
by an adaptive search based on Gaussian Processes and Probability of
Improvement. Applying this method on a large and varied MRI dataset, we show a
substantial improvement between the baseline network and the final one (up to
20\% for the most difficult classes).

Score: 0.65219975

Summary:  The classification of MRI images according to the anatomical field of view is a necessary task to solve when faced with the increasing quantity of medical images. Using a common architecture (such as AlexNet) provides quite good results, but not sufficient for clinical use.

Title:  High-Resolution Breast Cancer Screening with Multi-View Deep
  Convolutional Neural Networks
Title   Advances in deep learning for natural images have prompted a surge of
interest in applying similar techniques to medical images. The majority of the
initial attempts focused on replacing the input of a deep convolutional neural
network with a medical image, which does not take into consideration the
fundamental differences between these two types of images. Specifically, fine
details are necessary for detection in medical images, unlike in natural images
where coarse structures matter most. Th
Abstract:    Advances in deep learning for natural images have prompted a surge of
interest in applying similar techniques to medical images. The majority of the
initial attempts focused on replacing the input of a deep convolutional neural
network with a medical image, which does not take into consideration the
fundamental differences between these two types of images. Specifically, fine
details are necessary for detection in medical images, unlike in natural images
where coarse structures matter most. This difference makes it inadequate to use
the existing network architectures developed for natural images, because they
work on heavily downscaled images to reduce the memory requirements. This hides
details necessary to make accurate predictions. Additionally, a single exam in
medical imaging often comes with a set of views which must be fused in order to
reach a correct conclusion. In our work, we propose to use a multi-view deep
convolutional neural network that handles a set of high-resolution medical
images. We evaluate it on large-scale mammography-based breast cancer screening
(BI-RADS prediction) using 886,000 images. We focus on investigating the impact
of the training set size and image size on the prediction accuracy. Our results
highlight that performance increases with the size of training set, and that
the best performance can only be achieved using the original resolution. In the
reader study, performed on a random subset of the test set, we confirmed the
efficacy of our model, which achieved performance comparable to a committee of
radiologists when presented with the same data.

Score: 0.62811744

Summary:  The study used a set of high-resolution images to test the accuracy of the neural network. It found that the network performed better than expected when it was given a large set of images to work with.

Title:  Deep Learning for the Classification of Lung Nodules
Title   Deep learning, as a promising new area of machine learning, has attracted a
rapidly increasing attention in the field of medical imaging. Compared to the
conventional machine learning methods, deep learning requires no hand-tuned
feature extractor, and has shown a superior performance in many visual object
recognition applications. In this study, we develop a deep convolutional neural
network (CNN) and apply it to thoracic CT images for the classification of lung
nodules. We present the CNN ar
Abstract:    Deep learning, as a promising new area of machine learning, has attracted a
rapidly increasing attention in the field of medical imaging. Compared to the
conventional machine learning methods, deep learning requires no hand-tuned
feature extractor, and has shown a superior performance in many visual object
recognition applications. In this study, we develop a deep convolutional neural
network (CNN) and apply it to thoracic CT images for the classification of lung
nodules. We present the CNN architecture and classification accuracy for the
original images of lung nodules. In order to understand the features of lung
nodules, we further construct new datasets, based on the combination of
artificial geometric nodules and some transformations of the original images,
as well as a stochastic nodule shape model. It is found that simplistic
geometric nodules cannot capture the important features of lung nodules.

Score: 0.61311525

Summary:  Deep learning, as a promising new area of machine learning, has attracted a rapidly increasing attention in the field of medical imaging. In this study, we develop a deep convolutional neuralnetwork (CNN) and apply it to thoracic CT images for the classification of lung nodules.

In [65]:
def search_and_summarize(query,k=5):
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  for score,idx in zip(D[0],I[0]):
    print('Title: ',df.iloc[idx]["title"])
    print('Title',df.iloc[idx]['abstract'][:500])
    print('Abstract: ',df.iloc[idx]["abstract"])
    print('Score:', score)
    print()
    summary=summarizer(df.iloc[idx]['abstract'],max_length=120,min_length=40,do_sample=False)
    print('Summary: ',summary[0]['summary_text'])
    print()

In [66]:
search_and_summarize('Deep learning in medical imaging',k=5)

Title:  A Perspective on Deep Imaging
Title   The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance
Abstract:    The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance in clinical and
preclinical applications. To realize the full impact of machine learning on
medical imaging, major challenges must be addressed.

Score: 0.73549855

Summary:  The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.

Title:  Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection
Title   The classification of MRI images according to the anatomical field of view is
a necessary task to solve when faced with the increasing quantity of medical
images. In parallel, advances in deep learning makes it a suitable tool for
computer vision problems. Using a common architecture (such as AlexNet)
provides quite good results, but not sufficient for clinical use. Improving the
model is not an easy task, due to the large number of hyper-parameters
governing both the architecture and the trai
Abstract:    The classification of MRI images according to the anatomical field of view is
a necessary task to solve when faced with the increasing quantity of medical
images. In parallel, advances in deep learning makes it a suitable tool for
computer vision problems. Using a common architecture (such as AlexNet)
provides quite good results, but not sufficient for clinical use. Improving the
model is not an easy task, due to the large number of hyper-parameters
governing both the architecture and the training of the network, and to the
limited understanding of their relevance. Since an exhaustive search is not
tractable, we propose to optimize the network first by random search, and then
by an adaptive search based on Gaussian Processes and Probability of
Improvement. Applying this method on a large and varied MRI dataset, we show a
substantial improvement between the baseline network and the final one (up to
20\% for the most difficult classes).

Score: 0.6881736

Summary:  The classification of MRI images according to the anatomical field of view is a necessary task to solve when faced with the increasing quantity of medical images. Using a common architecture (such as AlexNet) provides quite good results, but not sufficient for clinical use.

Title:  Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?
Title   Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure proper convergence. A promising alternative is to fine-tune
a CNN that has been pre-trained using, for instance, a large set of labeled
natural images. However, the substantial differences between natural and
medical images may advise against such knowledge transfer. In this paper, we
seek to answer the following centra
Abstract:    Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure proper convergence. A promising alternative is to fine-tune
a CNN that has been pre-trained using, for instance, a large set of labeled
natural images. However, the substantial differences between natural and
medical images may advise against such knowledge transfer. In this paper, we
seek to answer the following central question in the context of medical image
analysis: \emph{Can the use of pre-trained deep CNNs with sufficient
fine-tuning eliminate the need for training a deep CNN from scratch?} To
address this question, we considered 4 distinct medical imaging applications in
3 specialties (radiology, cardiology, and gastroenterology) involving
classification, detection, and segmentation from 3 different imaging
modalities, and investigated how the performance of deep CNNs trained from
scratch compared with the pre-trained CNNs fine-tuned in a layer-wise manner.
Our experiments consistently demonstrated that (1) the use of a pre-trained CNN
with adequate fine-tuning outperformed or, in the worst case, performed as well
as a CNN trained from scratch; (2) fine-tuned CNNs were more robust to the size
of training sets than CNNs trained from scratch; (3) neither shallow tuning nor
deep tuning was the optimal choice for a particular application; and (4) our
layer-wise fine-tuning scheme could offer a practical way to reach the best
performance for the application at hand based on the amount of available data.

Score: 0.6532082

Summary:  Training a deep convolutional neural network from scratch is difficult because it requires a large amount of labeled training data. A promising alternative is to fine-tune a CNN that has been pre-trained using, for instance, a large set of labeled natural images.

Title:  High-Resolution Breast Cancer Screening with Multi-View Deep
  Convolutional Neural Networks
Title   Advances in deep learning for natural images have prompted a surge of
interest in applying similar techniques to medical images. The majority of the
initial attempts focused on replacing the input of a deep convolutional neural
network with a medical image, which does not take into consideration the
fundamental differences between these two types of images. Specifically, fine
details are necessary for detection in medical images, unlike in natural images
where coarse structures matter most. Th
Abstract:    Advances in deep learning for natural images have prompted a surge of
interest in applying similar techniques to medical images. The majority of the
initial attempts focused on replacing the input of a deep convolutional neural
network with a medical image, which does not take into consideration the
fundamental differences between these two types of images. Specifically, fine
details are necessary for detection in medical images, unlike in natural images
where coarse structures matter most. This difference makes it inadequate to use
the existing network architectures developed for natural images, because they
work on heavily downscaled images to reduce the memory requirements. This hides
details necessary to make accurate predictions. Additionally, a single exam in
medical imaging often comes with a set of views which must be fused in order to
reach a correct conclusion. In our work, we propose to use a multi-view deep
convolutional neural network that handles a set of high-resolution medical
images. We evaluate it on large-scale mammography-based breast cancer screening
(BI-RADS prediction) using 886,000 images. We focus on investigating the impact
of the training set size and image size on the prediction accuracy. Our results
highlight that performance increases with the size of training set, and that
the best performance can only be achieved using the original resolution. In the
reader study, performed on a random subset of the test set, we confirmed the
efficacy of our model, which achieved performance comparable to a committee of
radiologists when presented with the same data.

Score: 0.62220883

Summary:  The study used a set of high-resolution images to test the accuracy of the neural network. It found that the network performed better than expected when it was given a large set of images to work with.

Title:  Deep Learning Microscopy
Title   We demonstrate that a deep neural network can significantly improve optical
microscopy, enhancing its spatial resolution over a large field-of-view and
depth-of-field. After its training, the only input to this network is an image
acquired using a regular optical microscope, without any changes to its design.
We blindly tested this deep learning approach using various tissue samples that
are imaged with low-resolution and wide-field systems, where the network
rapidly outputs an image with rema
Abstract:    We demonstrate that a deep neural network can significantly improve optical
microscopy, enhancing its spatial resolution over a large field-of-view and
depth-of-field. After its training, the only input to this network is an image
acquired using a regular optical microscope, without any changes to its design.
We blindly tested this deep learning approach using various tissue samples that
are imaged with low-resolution and wide-field systems, where the network
rapidly outputs an image with remarkably better resolution, matching the
performance of higher numerical aperture lenses, also significantly surpassing
their limited field-of-view and depth-of-field. These results are
transformative for various fields that use microscopy tools, including e.g.,
life sciences, where optical microscopy is considered as one of the most widely
used and deployed techniques. Beyond such applications, our presented approach
is broadly applicable to other imaging modalities, also spanning different
parts of the electromagnetic spectrum, and can be used to design computational
imagers that get better and better as they continue to image specimen and
establish new transformations among different modes of imaging.

Score: 0.6151297

Summary:  We demonstrate that a deep neural network can significantly improve opticalmicroscopy. After its training, the only input to this network is an imageacquired using a regular optical microscope, without any changes to its design. These results are transformative for various fields that use microscopy tools.

In [67]:
!pip install keybert==0.8.5

Collecting keybert==0.8.5
  Downloading keybert-0.8.5-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from keybert==0.8.5) (2.0.2)
Requirement already satisfied: rich>=10.4.0 in /usr/local/lib/python3.12/dist-packages (from keybert==0.8.5) (13.9.4)
Requirement already satisfied: scikit-learn>=0.22.2 in /usr/local/lib/python3.12/dist-packages (from keybert==0.8.5) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.3.8 in /usr/local/lib/python3.12/dist-packages (from keybert==0.8.5) (5.6.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.4.0->keybert==0.8.5) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.4.0->keybert==0.8.5) (2.20.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.2->keybert==0.8.5) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.2->keybert==0.8.5) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.2->keybert==0.8.5) (3.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert==0.8.5) (4.46.3)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert==0.8.5) (0.36.2)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert==0.8.5) (2.11.0+cpu)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert==0.8.5) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert==0.8.5) (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.29.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (1.5.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (2.32.4)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.4.0->keybert==0.8.5) (0.1.2)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert==0.8.5) (2025.11.3)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert==0.8.5) (0.20.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert==0.8.5) (0.8.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (2026.6.17)
Downloading keybert-0.8.5-py3-none-any.whl (37 kB)
Installing collected packages: keybert
Successfully installed keybert-0.8.5

In [68]:
from keybert import KeyBERT

In [69]:
kw_model=KeyBERT()

In [70]:
type(kw_model)

keybert._model.KeyBERT

In [71]:
text=df.iloc[10466]['abstract']

In [72]:
keywords=kw_model.extract_keywords(text)

In [73]:
print(keywords)

[('imaging', 0.4528), ('tomographic', 0.4488), ('reconstruction', 0.3623), ('deep', 0.3003), ('learning', 0.2622)]

In [74]:
keywords=kw_model.extract_keywords(text,keyphrase_ngram_range=(1,3),stop_words='english')

In [75]:
print(keywords)

[('tomographic imaging deep', 0.6704), ('imaging deep learning', 0.6543), ('learning medical imaging', 0.6041), ('imaging deep', 0.5919), ('medical imaging', 0.5281)]

In [76]:
def search_and_summarize(query,k=5):
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  for score,idx in zip(D[0],I[0]):
    print('Title: ',df.iloc[idx]["title"])
    print('Title',df.iloc[idx]['abstract'][:500])
    print('Abstract: ',df.iloc[idx]["abstract"])
    print('Score:', score)
    print()
    summary=summarizer(df.iloc[idx]['abstract'],max_length=120,min_length=40,do_sample=False)
    print('Summary: ',summary[0]['summary_text'])
    print()
    keywords=kw_model.extract_keywords(text,keyphrase_ngram_range=(1,3),stop_words='english')
    print(keywords)
    for k,s in keywords:
      print(k)

NER,

In [77]:
!pip install spacy
!python -m spacy download en_core_web_sm

Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.14)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.25.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.13.4)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (26.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.6.17)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (8.4.2)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.24.0)
Requirement already satisfied: smart-open>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (7.6.1)
Requirement already satisfied: httpx>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.14.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.20.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (2.2.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 29.4 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [85]:
import spacy

nlp = spacy.load("en_core_web_sm")

In [86]:
useful_labels = [
    "ORG", "PERSON", "GPE", "LOC",
    "DATE", "PRODUCT", "EVENT",
    "WORK_OF_ART", "NORP", "FAC"
]

def find_entities(text):

    doc = nlp(text)

    entities = []
    seen = []

    for entity in doc.ents:

        if entity.label_ in useful_labels:

            if entity.text not in seen:

                entities.append({
                    "name": entity.text,
                    "type": entity.label_,
                    "description": spacy.explain(entity.label_)
                })

                seen.append(entity.text)

    return entities

In [87]:
example_text = "Google was founded by Larry Page and Sergey Brin in California on September 4, 1998. The company is headquartered in Mountain View."
entities = find_entities(example_text)
print("Extracted Entities:")
for entity in entities:
    print(f"\nName: {entity['name']}")
    print(f"Type: {entity['type']}")
    print(f"Description: {entity['description']}")

Extracted Entities:

Name: Google
Type: ORG
Description: Companies, agencies, institutions, etc.

Name: Larry Page
Type: PERSON
Description: People, including fictional

Name: Sergey Brin
Type: PERSON
Description: People, including fictional

Name: California
Type: GPE
Description: Countries, cities, states

Name: September 4, 1998
Type: DATE
Description: Absolute or relative dates or periods

Name: Mountain View
Type: GPE
Description: Countries, cities, states

In [88]:




def search_with_keywords_and_entities(query, k=5):

    # Convert query into embedding
    query_vector = model.encode([query])
    faiss.normalize_L2(query_vector)

    scores, indexes = index.search(query_vector, k)
    for score, paper_index in zip(scores[0], indexes[0]):
        paper = df.iloc[paper_index]
        title = paper["title"]
        abstract = paper["abstract"]
        full_text = title + " " + abstract
        keywords = kw_model.extract_keywords(
            full_text,
            keyphrase_ngram_range=(1, 3),
            stop_words="english",
            top_n=10
        )
        entities = find_entities(full_text)
        summary = summarizer(
            abstract,
            max_length=120,
            min_length=40,
            do_sample=False
        )
        print("=" * 80)
        print(f"Similarity Score : {score:.4f}")
        print("\nTitle")
        print(title)
        print("\nAbstract")
        print(abstract)
        print("\nSummary")
        print(summary[0]["summary_text"])
        print("\nKeywords")
        if keywords:
            for keyword, _ in keywords:
                print(f"- {keyword}")
        else:
            print("No keywords found.")
        print("\nNamed Entities")
        if entities:
            for entity in entities:
                print(f"- {entity['name']} ({entity['type']})")
        else:
            print("No named entities found.")
        print("\n")

In [89]:
search_with_keywords_and_entities("Deep learning in medical imaging", k=5)

================================================================================
Similarity Score : 0.7355

Title
A Perspective on Deep Imaging

Abstract
  The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance in clinical and
preclinical applications. To realize the full impact of machine learning on
medical imaging, major challenges must be addressed.


Summary
The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.

Keywords
- imaging deep learning
- tomographic imaging deep
- deep imaging
- imaging deep
- learning medical imaging
- deep imaging combination
- medical imaging
- image reconstruction superior
- medical imaging develop
- image reconstruction aspect

Named Entities
No named entities found.


================================================================================
Similarity Score : 0.6882

Title
Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection

Abstract
  The classification of MRI images according to the anatomical field of view is
a necessary task to solve when faced with the increasing quantity of medical
images. In parallel, advances in deep learning makes it a suitable tool for
computer vision problems. Using a common architecture (such as AlexNet)
provides quite good results, but not sufficient for clinical use. Improving the
model is not an easy task, due to the large number of hyper-parameters
governing both the architecture and the training of the network, and to the
limited understanding of their relevance. Since an exhaustive search is not
tractable, we propose to optimize the network first by random search, and then
by an adaptive search based on Gaussian Processes and Probability of
Improvement. Applying this method on a large and varied MRI dataset, we show a
substantial improvement between the baseline network and the final one (up to
20\% for the most difficult classes).


Summary
The classification of MRI images according to the anatomical field of view is a necessary task to solve when faced with the increasing quantity of medical images. Using a common architecture (such as AlexNet) provides quite good results, but not sufficient for clinical use.

Keywords
- deep learning gaussian
- classification mri
- selection classification mri
- classification mri images
- mri dataset substantial
- classification mri data
- mri dataset
- advances deep learning
- varied mri dataset
- deep learning

Named Entities
- Deep Learning (ORG)
- Gaussian
  Process (PERSON)
- Model Selection (PRODUCT)
- AlexNet (ORG)
- Gaussian Processes and Probability (ORG)


================================================================================
Similarity Score : 0.6532

Title
Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?

Abstract
  Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure proper convergence. A promising alternative is to fine-tune
a CNN that has been pre-trained using, for instance, a large set of labeled
natural images. However, the substantial differences between natural and
medical images may advise against such knowledge transfer. In this paper, we
seek to answer the following central question in the context of medical image
analysis: \emph{Can the use of pre-trained deep CNNs with sufficient
fine-tuning eliminate the need for training a deep CNN from scratch?} To
address this question, we considered 4 distinct medical imaging applications in
3 specialties (radiology, cardiology, and gastroenterology) involving
classification, detection, and segmentation from 3 different imaging
modalities, and investigated how the performance of deep CNNs trained from
scratch compared with the pre-trained CNNs fine-tuned in a layer-wise manner.
Our experiments consistently demonstrated that (1) the use of a pre-trained CNN
with adequate fine-tuning outperformed or, in the worst case, performed as well
as a CNN trained from scratch; (2) fine-tuned CNNs were more robust to the size
of training sets than CNNs trained from scratch; (3) neither shallow tuning nor
deep tuning was the optimal choice for a particular application; and (4) our
layer-wise fine-tuning scheme could offer a practical way to reach the best
performance for the application at hand based on the amount of available data.


Summary
Training a deep convolutional neural network from scratch is difficult because it requires a large amount of labeled training data. A promising alternative is to fine-tune a CNN that has been pre-trained using, for instance, a large set of labeled natural images.

Keywords
- cnns sufficient fine
- trained cnns fine
- cnn adequate fine
- fine tune cnn
- cnns fine tuned
- fine tuned cnns
- training deep cnn
- pre trained cnns
- cnn pre trained
- trained cnn adequate

Named Entities
- Convolutional Neural Networks for Medical Image Analysis (ORG)
- CNN (ORG)


================================================================================
Similarity Score : 0.6222

Title
High-Resolution Breast Cancer Screening with Multi-View Deep
  Convolutional Neural Networks

Abstract
  Advances in deep learning for natural images have prompted a surge of
interest in applying similar techniques to medical images. The majority of the
initial attempts focused on replacing the input of a deep convolutional neural
network with a medical image, which does not take into consideration the
fundamental differences between these two types of images. Specifically, fine
details are necessary for detection in medical images, unlike in natural images
where coarse structures matter most. This difference makes it inadequate to use
the existing network architectures developed for natural images, because they
work on heavily downscaled images to reduce the memory requirements. This hides
details necessary to make accurate predictions. Additionally, a single exam in
medical imaging often comes with a set of views which must be fused in order to
reach a correct conclusion. In our work, we propose to use a multi-view deep
convolutional neural network that handles a set of high-resolution medical
images. We evaluate it on large-scale mammography-based breast cancer screening
(BI-RADS prediction) using 886,000 images. We focus on investigating the impact
of the training set size and image size on the prediction accuracy. Our results
highlight that performance increases with the size of training set, and that
the best performance can only be achieved using the original resolution. In the
reader study, performed on a random subset of the test set, we confirmed the
efficacy of our model, which achieved performance comparable to a committee of
radiologists when presented with the same data.


Summary
The study used a set of high-resolution images to test the accuracy of the neural network. It found that the network performed better than expected when it was given a large set of images to work with.

Keywords
- view deep convolutional
- multi view deep
- deep convolutional
- deep learning natural
- deep convolutional neural
- learning natural images
- networks advances deep
- view deep
- input deep convolutional
- large scale mammography

Named Entities
No named entities found.


================================================================================
Similarity Score : 0.6151

Title
Deep Learning Microscopy

Abstract
  We demonstrate that a deep neural network can significantly improve optical
microscopy, enhancing its spatial resolution over a large field-of-view and
depth-of-field. After its training, the only input to this network is an image
acquired using a regular optical microscope, without any changes to its design.
We blindly tested this deep learning approach using various tissue samples that
are imaged with low-resolution and wide-field systems, where the network
rapidly outputs an image with remarkably better resolution, matching the
performance of higher numerical aperture lenses, also significantly surpassing
their limited field-of-view and depth-of-field. These results are
transformative for various fields that use microscopy tools, including e.g.,
life sciences, where optical microscopy is considered as one of the most widely
used and deployed techniques. Beyond such applications, our presented approach
is broadly applicable to other imaging modalities, also spanning different
parts of the electromagnetic spectrum, and can be used to design computational
imagers that get better and better as they continue to image specimen and
establish new transformations among different modes of imaging.


Summary
We demonstrate that a deep neural network can significantly improve opticalmicroscopy. After its training, the only input to this network is an imageacquired using a regular optical microscope, without any changes to its design. These results are transformative for various fields that use microscopy tools.

Keywords
- deep learning microscopy
- learning microscopy
- improve optical microscopy
- microscopy demonstrate deep
- fields use microscopy
- learning microscopy demonstrate
- optical microscopy
- optical microscopy enhancing
- sciences optical microscopy
- microscopy

Named Entities
- Deep Learning Microscopy (PERSON)